accelerator: auto
strategy: auto
devices: [0]
num_nodes: 1
enable_model_summary: true
max_epochs: 5
deterministic: true
logger:
  - class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: tensorboard_logs/
      name: road_condition
  - class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: csv_logs/
      name: road_visibility
